feat(RHINENG-7106): update doc links to use 1-latest subpath
RedHatInsights/registration-assistant pull request #99
Opened 2024-03-20 12:32 UTC by mkholjuraev

Updates all doc links using 2023 to use the new subpath 1-latest. 

1. Make sure no more doc links are left that use a year as a subpath
2. Make sure all changes linked redirect properly

2024-03-22 14:16 UTC, Fewwy requested changes

2024-03-27 10:18 UTC, mkholjuraev commented on src/Routes/Register/Helpers.js
> +          <a href="https://access.redhat.com/documentation/en-us/red_hat_insights/1-latest/html/configuring_basic_authentication_for_red_hat_insights/index">
waiting for the proper link to be given

2024-03-28 16:32 UTC, mkholjuraev commented on src/Routes/Register/Helpers.js
> +          <a href="https://access.redhat.com/documentation/en-us/red_hat_insights/1-latest/html/configuring_basic_authentication_for_red_hat_insights/index">
@Fewwy The PM has decided that we will live with this dead link for some time. Then this dead link will be removed while we are working on this ticket [RHINENG-8921](https://issues.redhat.com/browse/RHINENG-8921). So, please have another look, if everything is fine except this link, we can merge it

2024-03-31 20:43 UTC, Fewwy approved these changes

2024-03-31 20:43 UTC, Fewwy commented on src/Routes/Register/Helpers.js
> +          <a href="https://access.redhat.com/documentation/en-us/red_hat_insights/1-latest/html/configuring_basic_authentication_for_red_hat_insights/index">
@mkholjuraev I approved PR

2024-04-01 14:56 UTC, merged